spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:33306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database: mysql
    properties:
      hibernate:
        hbm2ddl.auto: none
